import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import './globals.css'

export const metadata: Metadata = {
  title: 'EduForge — AI Content Generator',
  description: 'Generate professional PPTs, notes, exercises and articles with AI in seconds.',
  keywords: 'AI presentation generator, study notes, exercises, LinkedIn article, Gemini AI',
  openGraph: {
    title: 'EduForge — AI Content Generator',
    description: 'PPTs, notes, exercises and articles generated by AI in seconds.',
    type: 'website',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              borderRadius: '14px',
              background: 'rgba(255,255,255,0.9)',
              backdropFilter: 'blur(20px)',
              border: '1px solid rgba(99,102,241,0.15)',
              color: '#1e1b4b',
              fontFamily: '-apple-system, BlinkMacSystemFont, SF Pro Display, sans-serif',
              boxShadow: '0 8px 32px rgba(99,102,241,0.12)',
            },
            success: { iconTheme: { primary: '#10b981', secondary: 'white' } },
            error: { iconTheme: { primary: '#ef4444', secondary: 'white' } },
          }}
        />
        {children}
      </body>
    </html>
  )
}
